Time: 1-1.5h

Content:
- Recap: what is weak supervision
- Labeling function output
- Two label model: Majority Vote, FABLE
- A simple classifier 
- Label Model: Snorkel / smth. Newer
- Decide if Lin. Reg / BERT / both
- E2E model? SepLL    (if time permits only)

To think about:
- prepare additional files (packages, incl. wrench, instruction how to create a venv, datasets - spam, yoruba + instruction how to access wrench datasets)

In [149]:
!python --version

Python 3.8.3


In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

# Tutorial: How to train a classifier using Weak Supervision?

In [176]:
import pandas as pd
import numpy as np 

from snorkel.utils import probs_to_preds
from utils import load_raw_spam_dataset
from wrench.endmodel import EndClassifierModel
from wrench.labelmodel import MajorityVoting, Fable
from wrench.utils import set_seed

path_to_data = "data"
# os.chdir("wrench/spam")

In this tutorial, we are going to train a spam detection classifier using weak supervision. The dataset we will use for training is Spam Detection YouTube comments dataset. 

Some info about the dataset:
- The dataset consists of comments that YouTube users left under different videos.
- Each sample is a comment (i.e., a word, a sentence, or a couple of sentences).
- 1,586 train samples, 120 dev samples, 250 test samples
- There are 2 types of samples:
    - HAM: comments relevant to the video (even very simple ones), or
    - SPAM: irrelevant (often trying to advertise something) or inappropriate messages
- Original dataset is labeled; we are going to use it as unlabeled one (and label it in a weakly-supervised fasion). 

Let's first have a look at the unlabeled dataset.

In [3]:
# load the YouTube dataset
df_train, df_dev, df_test = load_raw_spam_dataset(load_train_labels=True)
Y_train = df_train["label"].values
Y_test = df_test["label"].values

In [4]:
df_train[:10]

author                 date  \
0  Alessandro leite  2014-11-05T22:21:36   
1      Salim Tayara  2014-11-02T14:33:30   
2           Phuc Ly  2014-01-20T15:27:47   
3      DropShotSk8r  2014-01-19T04:27:18   
4            css403  2014-11-07T14:25:48   
5      Giang Nguyen  2014-11-06T04:55:41   
6      Caius Ballad  2014-11-13T00:58:20   
7             Holly  2014-11-06T13:41:30   
8         King uzzy  2014-11-07T23:19:08   
9          iKap Taz  2014-11-08T13:34:27   

                                                                                                                  text  \
0                          pls http://www10.vakinha.com.br/VaquinhaE.aspx?e=313327 help me get vip gun  cross fire al   
1  if your like drones, plz subscribe to Kamal Tayara. He takes videos with  his drone that are absolutely beautiful.   
2                                                                                       go here to check the views :3   
3                                                                              Came here to check the views, goodbye.   
4                                                                                        i am 2,126,492,636 viewer :D   
5                                                                                  https://www.facebook.com/teeLaLaLa   
6                                  imagine if this guy put adsense on with all these views... u could pay ur  morgage   
7                                                                                Follow me on Twitter @mscalifornia95   
8                                                                     Can we reach 3 billion views by December 2014?    
9                                             Follow 4 Follow                           @ VaahidMustafic Like 4 Like    

   label  video  
0      1      1  
1      1      1  
2      0      1  
3      0      1  
4      0      1  
5      1      1  
6      0      1  
7      1      1  
8      0      1  
9      1      1

For each data sample (i.e., a YouTube comment), we know:
- comment's author,
- date when the corresponding comment was left,
- text of the sample,
- label,
- id of the YouTube video.

Examples of HAM messages (label = 0):
- "3:46 so cute!"
- "This is a weird video."

In [5]:
# some examples of positive (=non-spam) samples

df_train.loc[df_train["label"]==0][:10]

author                 date  \
2         Phuc Ly  2014-01-20T15:27:47   
3    DropShotSk8r  2014-01-19T04:27:18   
4          css403  2014-11-07T14:25:48   
6    Caius Ballad  2014-11-13T00:58:20   
8       King uzzy  2014-11-07T23:19:08   
10    John Plaatt  2014-11-07T22:22:29   
11  Praise Samuel  2014-11-08T11:10:30   
16   zhichao wang  2013-11-29T02:13:56   
19      Tedi Foto  2014-11-08T09:33:30   
20        Tee Tee  2014-11-07T20:16:51   

                                                                                                       text  \
2                                                                            go here to check the views :3   
3                                                                   Came here to check the views, goodbye.   
4                                                                             i am 2,126,492,636 viewer :D   
6                       imagine if this guy put adsense on with all these views... u could pay ur  morgage   
8                                                          Can we reach 3 billion views by December 2014?    
10                                                     On 0:02 u can see the camera man on his glasses....   
11  2 billion views wow not even baby by justin beibs has that much he doesn't  deserve a capitalized name   
16            i think about 100 millions of the views come from people who only wanted to  check the views   
19                                                                                   What my gangnam style   
20                                        Loool nice song funny how no one understands (me) and we love it   

    label  video  
2       0      1  
3       0      1  
4       0      1  
6       0      1  
8       0      1  
10      0      1  
11      0      1  
16      0      1  
19      0      1  
20      0      1

Examples of SPAM messages (label = 1):
- "Please check out my vidios"
- "Subscribe to me and I'll subscribe back!!!"

In [6]:
# some examples of negative (=spam) samples

df_train.loc[df_train["label"]==1][:10]

author                 date  \
0   Alessandro leite  2014-11-05T22:21:36   
1       Salim Tayara  2014-11-02T14:33:30   
5       Giang Nguyen  2014-11-06T04:55:41   
7              Holly  2014-11-06T13:41:30   
9           iKap Taz  2014-11-08T13:34:27   
12     Malin Linford  2014-11-05T01:13:43   
13       Lone Twistt  2013-11-28T17:34:55   
14         Олег Пась  2014-11-03T23:29:00   
15           JD COKE  2014-11-08T02:24:02   
17      Rancy Gaming  2014-11-06T09:41:07   

                                                                                                                                                                                                                                                                                                                                                                          text  \
0                                                                                                                                                                                                                                                                                  pls http://www10.vakinha.com.br/VaquinhaE.aspx?e=313327 help me get vip gun  cross fire al   
1                                                                                                                                                                                                                                                          if your like drones, plz subscribe to Kamal Tayara. He takes videos with  his drone that are absolutely beautiful.   
5                                                                                                                                                                                                                                                                                                                                          https://www.facebook.com/teeLaLaLa   
7                                                                                                                                                                                                                                                                                                                                        Follow me on Twitter @mscalifornia95   
9                                                                                                                                                                                                                                                                                                     Follow 4 Follow                           @ VaahidMustafic Like 4 Like    
12                                                                                                                                                                                                                              Hey guys please check out my new Google+ page it has many funny pictures,  FunnyTortsPics  https://plus.google.com/112720997191206369631/post   
13                                                                                                                                                                                          Once you have started reading do not stop. If you do not subscribe to me  within one day you and you're entire family will die so if you want to stay  alive subscribe right now.   
14                                                                                                                                                                                                                                                                                                                                                  Plizz withing my channel    
15  It's so hard, sad :( iThat little child Actor HWANG MINOO dancing very  active child is suffering from brain tumor, only 6 month left for him .Hard  to believe .. Keep praying everyone

Now let's imagine gold labels disappeared...

<img src="img/poof.jpg" width="400"/>

... and here we are: there is some data we want to use for classifier training, but we don't have any labels and capacity/time/money/... for hiring annotators.

But we can label this data with **weak supervision** :)

<img src="img/rainbow.png" width="700"/>

# Weak Supervision

A brief reminder how weak supervision works:
1. We come up with some heuristic rules and transform these rules into labeling functions.
2. We apply these labeling functions to the data and obtain weak labels.

TODO: add more here

### What can be a labeling function?

- Keyword searches: looking for specific words in a sentence
- Pattern matching: looking for specific syntactical patterns
- Third-party models: using an pre-trained model (usually a model for a different task than the one at hand)
- ...
- Crowdworker labels: treating each crowdworker as a black-box function that assigns labels to subsets of the data

*What labeling functions do you think are productive and useful to annotate the YouTube spam dataset?* 

*What rules might help to distinguish between spam and not-spam YouTube comments?*

*What patterns are typical for spam YouTube comments? for non-spam comments?*



Labeling Functions: 
1. ...
2. ...
3. ...
4. ...
5. ...
6. ...
7. ...
8. ...
9. ...
10. ...

### Rules into labeling functions

After we collected some rules, we transform them into labeling functions that could *label* the data sample - that is, assign it to one or another class. 

More examples of rules: 
- "check"/"check out": if there is a collocation "check out" in the comment, most probably this comment is spam (and the comment author is promoting his/her channel)
- "subscribe": same
- "my": same
- ...
 

In [7]:
# an example of LF based on a keyword "check out"

def check_out(x):
    return 1 if "check out" in x.text.lower() else -1

# meaning the sample will be assigned to class 1 (=SPAM) if there is a "check out" expression in the comment, 
# otherwise to class 0 (=non-SPAM)

In [8]:
# an example of LF based on a key word "please"

def check(x):
    return 1 if "please" in x.text.lower() else -1

# meaning the sample will be assigned to class 1 (=SPAM) if there is a "please" expression in the comment, 
# otherwise to class 0 (=non-SPAM)

### Labeling functions we are going to use

In this tutorial, we are going to use the labeling functions created by [Snorkel team](https://github.com/snorkel-team/snorkel-tutorials/blob/master/spam/01_spam_tutorial.ipynb), which are: 


1. keyword "my" (to detect spam comments like "my channel", "my video", etc)
2. keyword "subscribe" (to detect spam comments that ask users to subscribe to some channel)
3. keyword "http" (to detect spam comments that link to other channels)
4. keyword "please"/"plz" (to detect spam comments that make requests rather than commenting)
5. keyword "song" (to detect non-spam comments that actually talk about the video's content)
6. regex "check_out" (to detect spam comments like "check out this channel", etc)
7. short comment (non-spam comments are often short, such as 'cool video!')
8. mentioning specific people and are short (using SpaCy library; non-spam comments usually mention some people)
9. polarity (using TextBlob library; if polarity > 0.9, it is most probably a non-spam message)
10. subjectivity (using TextBlob library; if subjectivity >= 0.5, it is most probably a non-spam message)

(We are not going into details of the labeling process here now - you will hear more about it from my colleagues later). 

### Processed data

The resulted annotations can be saved in the following format: 

In [9]:
import json
with open("data/youtube/train.json") as train_file:
    train_data = json.load(train_file)
train_data["1"]

{'data': {'text': 'if your like drones, plz subscribe to Kamal Tayara. He takes videos with  his drone that are absolutely beautiful.\ufeff'},
 'label': 1,
 'weak_labels': [-1, 1, -1, 1, -1, -1, -1, -1, -1, 0]}

The structure of the processed data is the following: 
- data.text: the text of the sample
- label: gold label obtained by manual annotation
- weak_labels: the results of annotation by labeling functions. 
    - -1: the corresponding labeling function did not match
    - 0: the labeling function matched and assigned this sample to class 0 (non-spam class in our case)
    - 1: the labeling function matched and assigned this sample to class 1 (spam class in our case)

So, for the sample #1:
(*if your like drones, plz subscribe to Kamal Tayara. He takes videos with  his drone that are absolutely beautiful.\ufeff*)

- labeling functions 1, 3, 5, 6, 7, 8, 9 did not match
- labeling functions 2 (a key word *subscribe*) & 4 (a key word *plz*) matched and assigned this sample to the class 1
- labeling function 10 (subjectivity score > 0.5) matched and assigned this sample to the class 0

**Next step: how to turn these annotations into weak labels to train a classifier with them?**

## Weak labels

There are different *label models* that calculate the weak labels based on labeling functions annotations. In this tutorial, we are going to try two of them: 

- **Majority Vote** (intuitive and straightforward)
- **FABLE** [1] (most recent and well-performing)

For label calculation and model training we will use a weakly supervised framework called [Wrench](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiRmYabjOGAAxW1h_0HHQt3COQQFnoECA4QAQ&url=https%3A%2F%2Fgithub.com%2FJieyuZ2%2Fwrench&usg=AOvVaw3EWVM0icLVHENbUv51USa_&opi=89978449) [2].

### Wrench dataset

First, we transform our data into a Wrench-specific dataset. The data will be encoded with TF-IDF features. 

In [92]:
from wrench.dataset import load_dataset

train_data, valid_data, test_data = load_dataset(
    path_to_data,     # path to the folder where the dataset is stored
    "youtube",         # name of the dataset
    extract_feature=True,      # we want to encode out data ...
    extract_fn='tfidf'        # ... with TF-IDF features (other predefined options are 'sentence_transformer', 'bert')
)

  0%|          | 0/1586 [00:00<?, ?it/s]

  0%|          | 0/120 [00:00<?, ?it/s]

  0%|          | 0/250 [00:00<?, ?it/s]

Let's have a look what's inside. 

In [93]:
# the format of the train_data, valida_data, and test_data now is: wrench.dataset.dataset.TextDataset

train_data

In [94]:
# how many classes are there in the dataset?

train_data.n_class

2

In [95]:
# how many labeling functions are there in the dataset?

train_data.n_lf

10

In [96]:
# what is the class_id to class correspondence?

train_data.id2label

{0: 'HAM', 1: 'SPAM'}

In [97]:
# how do the samples look like?

train_data.examples[:10]

[{'text': 'pls http://www10.vakinha.com.br/VaquinhaE.aspx?e=313327 help me get vip gun  cross fire al\ufeff'},
 {'text': 'if your like drones, plz subscribe to Kamal Tayara. He takes videos with  his drone that are absolutely beautiful.\ufeff'},
 {'text': 'go here to check the views :3\ufeff'},
 {'text': 'Came here to check the views, goodbye.\ufeff'},
 {'text': 'i am 2,126,492,636 viewer :D\ufeff'},
 {'text': 'https://www.facebook.com/teeLaLaLa\ufeff'},
 {'text': 'imagine if this guy put adsense on with all these views... u could pay ur  morgage\ufeff'},
 {'text': 'Follow me on Twitter @mscalifornia95\ufeff'},
 {'text': 'Can we reach 3 billion views by December 2014? \ufeff'},
 {'text': 'Follow 4 Follow                           @ VaahidMustafic Like 4 Like \ufeff'}]

In [98]:
# how do the encoded samples look like?

print(type(train_data.features))
train_data.features[:10]

<class 'numpy.ndarray'>


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [101]:
# what are the weak annotations produced by labeling functions?

train_data.weak_labels[:10]

[[-1, -1, 1, -1, -1, -1, -1, -1, -1, -1],
 [-1, 1, -1, 1, -1, -1, -1, -1, -1, 0],
 [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
 [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
 [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
 [-1, -1, 1, -1, -1, -1, 0, -1, -1, -1],
 [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
 [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
 [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
 [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]]

### Majority Vote

The simplest and most straightforward method to calculate labels from the noisy annotations is **majority voting** - a decision-making method where the option with the most votes is chosen. It's like asking a group of people to pick a movie, and the one that gets the most hands raised wins. 

In our case, each labeling function produces a *vote*; the most voted class is selected as a sample label. All ties are broken randomly.


In [115]:
# initialize and fit the majority vote label model from the Wrench framework

label_model = MajorityVoting()
label_model.fit(dataset_train=train_data, dataset_valid=valid_data)

In [116]:
# calculate weak labels 

soft_label_mv = label_model.predict_proba(train_data)    # soft label as probabilities across all classes
hard_label_mv = probs_to_preds(soft_label_mv)               # hard labels as the most probable classes 

Let's look at the first 10 sentences, their weak annotations, and the weak labels obtained with majority voting. 

In [117]:
train_data.examples[:10]

[{'text': 'pls http://www10.vakinha.com.br/VaquinhaE.aspx?e=313327 help me get vip gun  cross fire al\ufeff'},
 {'text': 'if your like drones, plz subscribe to Kamal Tayara. He takes videos with  his drone that are absolutely beautiful.\ufeff'},
 {'text': 'go here to check the views :3\ufeff'},
 {'text': 'Came here to check the views, goodbye.\ufeff'},
 {'text': 'i am 2,126,492,636 viewer :D\ufeff'},
 {'text': 'https://www.facebook.com/teeLaLaLa\ufeff'},
 {'text': 'imagine if this guy put adsense on with all these views... u could pay ur  morgage\ufeff'},
 {'text': 'Follow me on Twitter @mscalifornia95\ufeff'},
 {'text': 'Can we reach 3 billion views by December 2014? \ufeff'},
 {'text': 'Follow 4 Follow                           @ VaahidMustafic Like 4 Like \ufeff'}]

In [118]:
train_data.weak_labels[:10]

[[-1, -1, 1, -1, -1, -1, -1, -1, -1, -1],
 [-1, 1, -1, 1, -1, -1, -1, -1, -1, 0],
 [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
 [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
 [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
 [-1, -1, 1, -1, -1, -1, 0, -1, -1, -1],
 [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
 [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
 [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
 [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]]

In [119]:
soft_label_mv[:10]

array([[0.        , 1.        ],
       [0.33333333, 0.66666667],
       [0.5       , 0.5       ],
       [0.5       , 0.5       ],
       [0.5       , 0.5       ],
       [0.5       , 0.5       ],
       [0.5       , 0.5       ],
       [0.5       , 0.5       ],
       [0.5       , 0.5       ],
       [0.5       , 0.5       ]])

In [138]:
hard_label_mv[:10]

array([1, 1, 0, 1, 0, 0, 0, 0, 1, 1])

### FABLE 

todo: a small description

In [121]:
# initialize and apply the fable model

label_model = Fable(kernel_function=None, num_groups=3)
label_model.fit(dataset_train=train_data, dataset_valid=valid_data)

NaN values included: []


  0%|▏                                                                                                        | 2/1000 [00:06<50:24,  3.03s/iter]

stop


array([[0.5145591 , 0.4854409 ],
       [0.06758916, 0.93241084],
       [0.57572972, 0.42427028],
       ...,
       [0.01319678, 0.98680322],
       [0.0777692 , 0.9222308 ],
       [0.00474839, 0.99525161]])

In [194]:
# calculate labels
soft_label_fable = label_model.predict_proba(train_data)
hard_label_fable = probs_to_preds(soft_label_fable)

  0%|▏                                                                                                        | 2/1000 [00:06<50:45,  3.05s/iter]

stop


In [195]:
soft_label_fable[:10]

array([[0.65702469, 0.34297531],
       [0.03282897, 0.96717103],
       [0.58049888, 0.41950112],
       [0.58015256, 0.41984744],
       [0.56159823, 0.43840177],
       [0.93658837, 0.06341163],
       [0.56569768, 0.43430232],
       [0.60110809, 0.39889191],
       [0.58510639, 0.41489361],
       [0.55216604, 0.44783396]])

In [196]:
hard_label_fable[:10]

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

## Classifier training

In [ ]:
batch_size = 32
test_batch_size = 32
lr = 0.01

Train a classifier on majorty vote **soft** labels.

In [201]:
set_seed(42)

# initialize a classifier
model = EndClassifierModel(
    batch_size=batch_size, test_batch_size=test_batch_size
)

# fit it 
model.fit(
    dataset_train=train_data, 
    y_train=soft_label_mv, 
    dataset_valid=valid_data, 
    verbose=False
)

# test on the test set
model.test(dataset=test_data, metric_fn="acc")

0.9

Train a classifier on majorty vote **hard** labels.

In [200]:
set_seed(42)

# initialize a classifier
model = EndClassifierModel(
    batch_size=batch_size, test_batch_size=test_batch_size
)

# fit it on the training data + majority vote hard labels
model.fit(
    dataset_train=train_data, 
    y_train=hard_label_mv, 
    dataset_valid=valid_data, 
    verbose=False
)

# test on the test set
model.test(dataset=test_data, metric_fn="acc")

0.92

Train a classifier on FABLE soft labels.

In [203]:
set_seed(42)

# initialize a classifier
model = EndClassifierModel(
    batch_size=batch_size, test_batch_size=test_batch_size
)

# fit it 
model.fit(
    dataset_train=train_data, 
    y_train=soft_label_fable, 
    dataset_valid=valid_data, 
    verbose=False
)

# test on the test set
model.test(dataset=test_data, metric_fn="acc")

0.9

Train a classifier on FABLE hard labels.

In [205]:
set_seed(42)

# initialize a classifier
model = EndClassifierModel(
    batch_size=batch_size, test_batch_size=test_batch_size
)

# fit it 
model.fit(
    dataset_train=train_data, 
    y_train=hard_label_fable, 
    dataset_valid=valid_data,
    verbose=False
)

# test on the test set
model.test(dataset=test_data, metric_fn="acc")

0.88

## Denoising

TODO: SepLL

# References

1. Zhang et al. 2023. Leveraging Instance Features for Label Aggregation in Programmatic Weak Supervision. 
2. Zhang et al. WRENCH: A Comprehensive Benchmark for Weak Supervision. 2021. https://arxiv.org/abs/2109.11377
